name: Download and Add File to Open-Profiles Repo

on:
  workflow_dispatch:

jobs:
  download-and-add-file:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout target repository
      uses: actions/checkout@v2
      with:
        repository: Repcz/Open-Profiles
        path: open-profiles-repo

    - name: Create target directory
      run: |
        mkdir -p open-profiles-repo/Rules
        ls -R open-profiles-repo/Rules
    
    - name: Download file
      run: |
        curl -L -o Apple.list "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Apple.list"
    
    - name: Move file to target directory
      run: |
        mv Apple.list open-profiles-repo/Rules/
    
    - name: Add and Commit
      run: |
        cd open-profiles-repo
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add Rules/Apple.list
        git commit -m "Add file"
        git push origin HEAD
