name: Copy Files

on:
  workflow_dispatch:

jobs:

  copy:

    runs-on: ubuntu-latest

    steps:
    
    - name: Checkout source repo
      uses: actions/checkout@v2  # You can continue to use this version
      with:
        repository: Repcz/ACL4SSR
        ref: master

    - name: Set up Git
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"

    - name: Copy files
      run: |
        mkdir -p ./Repcz/Open-Profiles/Surge/Rules
        cp ./Clash/Apple.list ./Repcz/Open-Profiles/Surge/Rules/apple.list
        cp ./Clash/ProxyGFWlist.list ./Repcz/Open-Profiles/Surge/Rules/proxy.list

    - name: Commit changes
      run: |
        cd ./Repcz/Open-Profiles/Surge/Rules
        git add -A
        git commit -m "Copy files from Repcz/ACL4SSR"

    - name: Push changes
      run: |
        cd ./Repcz/Open-Profiles/Surge/Rules
        git push https://github.com/Repcz/Open-Profiles.git master
      env:
        GITHUB_TOKEN: ${{ secrets.COPY_TOKEN }}
