name: Copy Files

on:
  workflow_dispatch:

jobs:

  copy:

    runs-on: ubuntu-latest

    steps:
    
    - name: Checkout source repo
      uses: actions/checkout@v2
      with:
        repository: Repcz/ACL4SSR
        ref: master

    - name: Copy files
      run: |
        mkdir -p ./Surge
        cp ./Clash/Apple.list ./Repcz/Open-Proflies/Surge/Rules/apple.list
        cp ./Clash/ProxyGFWlist.list ./Repcz/Open-Proflies/Surge/Rules/.list

    - name: Configure Git
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
      working-directory: ./Repcz/Open-Proflies/Surge/Rules

    - name: Commit changes
      run: |
        git add -A
        git commit -m "Copy files from ACL4SSR"
      working-directory: ./Repcz/Open-Proflies/Surge/Rules

    - name: Push changes
      run: |
        git push origin master
      env:
        GITHUB_TOKEN: ${{ secrets.COPY_TOKEN }}
      working-directory: ./Surge
